SELECT
    *
FROM
    ums_sys_menus
WHERE
    application = 'dsm_web'
  AND menu_category = 0
  AND menu_code != 'dsm_web'
	AND menu_code NOT REGEXP '^(dsmcp-|dsmc-|idm-|sdd-)'
	AND menu_code NOT REGEXP '^dsm-'
	AND menu_code IN (
		'sys-pivot',
		'dsmc-business-manage',
		'dsmc-compliance-result',
		'dsmc-compliance-strategy',
		'dsmc-compliance-task',
		'dsmc-compliance-template',
		'dsmc-controls-strategy',
		'dsmc-data-asset-app',
		'dsmc-data-asset-database',
		'dsmc-data-asset-file',
		'dsmc-data-asset-interface',
		'dsmc-data-asset-inventory',
		'dsmc-data-asset-record',
		'dsmc-data-monitor-situation',
		'dsmc-data-safety-govern',
		'dsmc-desensitization-strategy-details',
		'dsmc-desensitization-strategy-manage',
		'dsmc-life-cycle-task-details',
		'dsmc-life-cycle-task',
		'dsmc-operation-worktable',
		'dsmc-risk-strategy',
		'dsmc-safety-controls-standard',
		'dsmc-three-capacity',
		'dsmc-unknown-data-claim',
		'dsmc-user-data-auth',
		'dsmc-user-info-inventory',
		'dsmcp-ability-components-manage',
		'dsmcp-api-asset',
		'dsmcp-api-check-log',
		'dsmcp-app-asset-sensitive-list',
		'dsmcp-asset-approve',
		'dsmcp-audit-issue-dispose',
		'dsmcp-audit-report-history',
		'dsmcp-audit-report-task',
		'dsmcp-audit-report',
		'dsmcp-audit-safety-task',
		'dsmcp-audit-work-manage',
		'dsmcp-base-data-manage-indicator',
		'dsmcp-basic-data-archiving-result',
		'dsmcp-big-data-dynamic-ops',
		'dsmcp-code-security-audit',
		'dsmcp-compliance-approve-list',
		'dsmcp-compliance-assessment-template',
		'dsmcp-compliance-indictor',
		'dsmcp-compliance-job-approve',
		'dsmcp-compliance-job-archive',
		'dsmcp-compliance-job-issue',
		'dsmcp-compliance-job-report',
		'dsmcp-compliance-report-order',
		'dsmcp-compliance-report-task',
		'dsmcp-compliance-report-template',
		'dsmcp-compliance-template-manage',
		'dsmcp-data-admin',
		'dsmcp-data-asset-detect-warn',
		'dsmcp-data-asset-map',
		'dsmcp-data-asset-ops-target',
		'dsmcp-data-asset-view',
		'dsmcp-data-early-warning-view',
		'dsmcp-data-grade-control-policy',
		'dsmcp-data-life-cycle-mark',
		'dsmcp-data-monitor-situation',
		'dsmcp-data-safety-strategy-manage',
		'dsmcp-data-security-audit-list',
		'dsmcp-data-security-classification-inventory',
		'dsmcp-data-security-job-list',
		'dsmcp-data-security-risk-work-order-management',
		'dsmcp-data-security-template-manage',
		'dsmcp-dept',
		'dsmcp-dianxin-api-access-situation',
		'dsmcp-dianxin-api-asset-ledger',
		'dsmcp-dianxin-api-security-risk',
		'dsmcp-dianxin-data-asset-info',
		'dsmcp-dianxin-data-security-ledger',
		'dsmcp-dianxin-file-asset-info',
		'dsmcp-dianxin-info-system',
		'dsmcp-dianxin-report-record',
		'dsmcp-dianxin-risk-event-info',
		'dsmcp-dianxin-sensitive-data-field',
		'dsmcp-dianxin-sensitive-data-table',
		'dsmcp-dianxin-sensitive-file-info',
		'dsmcp-dianxin-task-manage',
		'dsmcp-disposal-process',
		'dsmcp-ds-analysis-warn-process',
		'dsmcp-ds-analysis-warn',
		'dsmcp-duty-manage-indicator',
		'dsmcp-emergency-exercise',
		'dsmcp-emergency-other-indicators',
		'dsmcp-estimate-template',
		'dsmcp-evaluation-report-management',
		'dsmcp-events-manage-detail',
		'dsmcp-events-manage',
		'dsmcp-external-api-manage',
		'dsmcp-external-interface-management',
		'dsmcp-external-interface-map',
		'dsmcp-external-interface-monitor',
		'dsmcp-fjgxt-data-situation',
		'dsmcp-full-flow-asset',
		'dsmcp-gd-disposal-fill-template',
		'dsmcp-gd-fill-order',
		'dsmcp-gd-fill-task',
		'dsmcp-gd-fill-template',
		'dsmcp-gd-risk-strategy',
		'dsmcp-gd-risk-white',
		'dsmcp-index-baseline-record',
		'dsmcp-indicator-baseline-statistics',
		'dsmcp-interface-account-audit-info',
		'dsmcp-interface-data-find-result',
		'dsmcp-interface-db-audit-log',
		'dsmcp-interface-security-controls-strategy',
		'dsmcp-interface-security-event-result',
		'dsmcp-interface-sensitive-log-collect',
		'dsmcp-interface-smp-app-asset',
		'dsmcp-interface-smp-data-asset',
		'dsmcp-interface-vault-log',
		'dsmcp-interface-vault-strategy',
		'dsmcp-ip-trace-query',
		'dsmcp-kb-data-identity-rule',
		'dsmcp-kb-data-security-event-dispose',
		'dsmcp-log-sensitive-audit',
		'dsmcp-management-center',
		'dsmcp-maturity-model',
		'dsmcp-mobile-report-data-asset',
		'dsmcp-mobile-report-data-event',
		'dsmcp-mobile-report-data-sensitive',
		'dsmcp-mobile-report-data-strategy',
		'dsmcp-mobile-report-dial-report',
		'dsmcp-network-ability-report',
		'dsmcp-network-accept-process',
		'dsmcp-network-api-asset',
		'dsmcp-network-classification',
		'dsmcp-network-core-data-list',
		'dsmcp-network-data-auth-list',
		'dsmcp-network-data-identification-rule',
		'dsmcp-network-data-report-record',
		'dsmcp-network-data-safety-task',
		'dsmcp-network-database-log',
		'dsmcp-network-detour-analysis',
		'dsmcp-network-duty-matrix',
		'dsmcp-network-important-data',
		'dsmcp-network-list-operation-log',
		'dsmcp-network-not-data-white-list',
		'dsmcp-network-problem-handle-and-track',
		'dsmcp-network-report-task',
		'dsmcp-network-resource-group',
		'dsmcp-network-security-event',
		'dsmcp-network-sensitization-system-list',
		'dsmcp-network-sensitization-user-list',
		'dsmcp-network-strategy-report',
		'dsmcp-not-desensitization-warning-whitelist',
		'dsmcp-not-desensitization-warning',
		'dsmcp-not-interface-find',
		'dsmcp-notice-send-manage',
		'dsmcp-operation-worktable',
		'dsmcp-partner-manage',
		'dsmcp-personal-worktable',
		'dsmcp-plaintext-transmit-warn',
		'dsmcp-qinghai-asset-group',
		'dsmcp-qinghai-asset',
		'dsmcp-qinghai-codes-of-practice',
		'dsmcp-qinghai-data-class-associate-data-model',
		'dsmcp-qinghai-data-classification',
		'dsmcp-qinghai-data-grade',
		'dsmcp-qinghai-data-model',
		'dsmcp-qinghai-data-security-policy',
		'dsmcp-qinghai-push-config',
		'dsmcp-qinghai-report-record',
		'dsmcp-qinghai-risk-event',
		'dsmcp-qinghai-sensitive-database-field',
		'dsmcp-qinghai-sensitive-database-file',
		'dsmcp-qinghai-sensitive-database-schema',
		'dsmcp-qinghai-sensitive-database-table',
		'dsmcp-rank-record-list',
		'dsmcp-raw-log-search',
		'dsmcp-risk-event-manage',
		'dsmcp-risk-factor',
		'dsmcp-risk-situation-view',
		'dsmcp-risk-survey-manage',
		'dsmcp-sc-assess-order',
		'dsmcp-sc-assess-task',
		'dsmcp-scc-fill-order',
		'dsmcp-scc-fill-task',
		'dsmcp-scc-fill-template',
		'dsmcp-sddx-audit-report-task',
		'dsmcp-security-compliance-chek-task-detail',
		'dsmcp-security-compliance-chek-task-report',
		'dsmcp-security-compliance-chek-task',
		'dsmcp-security-compliance-chek-work-detail',
		'dsmcp-security-compliance-inventory-tmpl',
		'dsmcp-security-standard-lib',
		'dsmcp-sensitive-asset-table-list',
		'dsmcp-sensitive-business-manage',
		'dsmcp-sensitive-data-api-task',
		'dsmcp-sensitive-data-audit',
		'dsmcp-sensitive-data-details',
		'dsmcp-sensitive-data-list',
		'dsmcp-sensitive-data-trace-task',
		'dsmcp-sensitive-data-view',
		'dsmcp-sensitive-list-foura',
		'dsmcp-sensitive-operation-log',
		'dsmcp-sensitive-people-view',
		'dsmcp-sensitive-table-auto-add-gold',
		'dsmcp-sensitive-treasury-list',
		'dsmcp-sensitive-user-auth',
		'dsmcp-sensitive-user-list',
		'dsmcp-service-admin-change',
		'dsmcp-shdx-home',
		'dsmcp-shdx-monitors',
		'dsmcp-situation-data-report',
		'dsmcp-smp-authorization',
		'dsmcp-strategy-manage-center',
		'dsmcp-system-access-foura-audit',
		'dsmcp-system-asset-sensitive-list',
		'dsmcp-system-type-mapping-manage',
		'dsmcp-system-warning-view',
		'dsmcp-telecom-asset-fill-details',
		'dsmcp-telecom-data-asset-report',
		'dsmcp-telecom-fill-work',
		'dsmcp-telecom-order-create',
		'dsmcp-telecom-system-fill-details',
		'dsmcp-telecom-system-report',
		'dsmcp-terminal-asset-manage',
		'dsmcp-terminal-filing-mapping',
		'dsmcp-terminal-mapping',
		'dsmcp-three-capacity-yinjian',
		'dsmcp-ueba-iframe-audit-alarm',
		'dsmcp-ueba-iframe-behavioral-session-manage',
		'dsmcp-ueba-iframe-cube-manage',
		'dsmcp-ueba-iframe-data-analysis',
		'dsmcp-ueba-iframe-data-collect',
		'dsmcp-ueba-iframe-equipment-analysis',
		'dsmcp-ueba-iframe-log-search',
		'dsmcp-ueba-iframe-operational-behavior-audit',
		'dsmcp-ueba-iframe-user-analysis',
		'dsmcp-unblock-account',
		'dsmcp-unknown-data-asset-whitelist-management',
		'dsmcp-warning-dispose-detail',
		'dsmcp-warning-dispose-work-process',
		'dsmcp-warning-dispose',
		'dsmcp-xinan-common-data-asset-list',
		'dsmcp-xinan-data-external-cooperation',
		'dsmcp-xinan-data-report-record',
		'dsmcp-xinan-data-security-protection-building',
		'dsmcp-xinan-data-security-risk-dispose',
		'dsmcp-xinan-ds-education-train-record',
		'dsmcp-xinan-ds-emergency-drill-record',
		'dsmcp-xinan-ds-institution-leader',
		'dsmcp-xinan-import-core-data-asset',
		'dsmcp-xinan-key-position-person',
		'dsmcp-xinan-report-task',
		'dsmcp-xinan-syslog-audit-report',
		'dsmcp-xinan-system-type-mapping-set',
		'idm-abnormal-flow',
		'idm-account-label',
		'idm-agent',
		'idm-ants-moving',
		'idm-app-api-manage',
		'idm-app-merge',
		'idm-app-split',
		'idm-asset-account-detail',
		'idm-asset-account',
		'idm-asset-app-detail',
		'idm-asset-app',
		'idm-asset-database-detail',
		'idm-asset-database',
		'idm-asset-email-detail',
		'idm-asset-email',
		'idm-asset-file-detail',
		'idm-asset-file',
		'idm-asset-foreign-interface-detail',
		'idm-asset-foreign-interface',
		'idm-asset-interface-detail',
		'idm-asset-interface',
		'idm-asset-ip-detail',
		'idm-asset-ip',
		'idm-asset-other-detail',
		'idm-asset-other',
		'idm-asset-screen',
		'idm-asset-unknown-other',
		'idm-asset-unknown',
		'idm-asset-visit',
		'idm-baseline-model',
		'idm-business-system-visit',
		'idm-business-system',
		'idm-business-user',
		'idm-category-grade-inventory',
		'idm-collect-strategy',
		'idm-config-email',
		'idm-critical-data-inventory',
		'idm-data-access-link',
		'idm-data-asset-map',
		'idm-data-backup',
		'idm-data-clear',
		'idm-data-dict',
		'idm-data-flow-distribution',
		'idm-data-flow-map',
		'idm-data-label',
		'idm-data-map',
		'idm-data-share-map',
		'idm-extract-account',
		'idm-extract-config',
		'idm-extract-keyword',
		'idm-file-manage',
		'idm-five-group-list',
		'idm-flow-monitor-detail',
		'idm-flow-monitor',
		'idm-grade-check',
		'idm-ignore-list',
		'idm-interface-label',
		'idm-interface-merge',
		'idm-log-relay',
		'idm-message-center',
		'idm-monitor-mode',
		'idm-monitor-task',
		'idm-network-segment',
		'idm-no-sensitive-access-detail',
		'idm-no-sensitive-access',
		'idm-notice-config',
		'idm-open-api',
		'idm-personal-inventory',
		'idm-probe-manage-deprecated',
		'idm-report-config',
		'idm-report-mould',
		'idm-report-operation',
		'idm-report-subscribe',
		'idm-resource-pool',
		'idm-risk-account',
		'idm-risk-database',
		'idm-risk-insight-event-detail',
		'idm-risk-insight-event',
		'idm-risk-interface',
		'idm-risk-label',
		'idm-risk-sourceip',
		'idm-risk-strategy',
		'idm-risk-white',
		'idm-sddx-app-api-manage',
		'idm-search-result',
		'idm-search',
		'idm-situation-sjwa',
		'idm-situation',
		'idm-sourceip-extract',
		'idm-systimesync',
		'idm-trace-analyse-reform',
		'idm-trace-analyse',
		'idm-trace-task-reform',
		'idm-trace-task',
		'idm-transfer-label',
		'idm-transform-baseline-model',
		'idm-trusted-inventory',
		'idm-tysl-app-api-manage',
		'idm-unknown-external-interface-identification',
		'idm-visit-account',
		'idm-visit-ip',
		'idm-visit-service',
		'idm-weakness-api',
		'idm-work-area',
		'idm-work-time',
		'sdd-asset-group',
		'sdd-audit-set',
		'sdd-auto-push-config',
		'sdd-business-priority',
		'sdd-class-grade-list-new',
		'sdd-class-grade-list',
		'sdd-class-grade-task-check-new',
		'sdd-class-grade-task-check-temp',
		'sdd-class-grade-task-check',
		'sdd-class-grade-task-new',
		'sdd-class-grade-task-temp',
		'sdd-class-grade-task',
		'sdd-class-grade-template-new',
		'sdd-class-grade-template',
		'sdd-classification-report',
		'sdd-compliance-detail',
		'sdd-compliance-process',
		'sdd-compliance-project-add',
		'sdd-compliance-project-edit',
		'sdd-compliance-project',
		'sdd-compliance-report',
		'sdd-compliance-task-add',
		'sdd-compliance-task-edit',
		'sdd-compliance-task',
		'sdd-core-data-list-new',
		'sdd-core-data-list',
		'sdd-data-assets-inventory',
		'sdd-data-assets-scan-detail-analysis',
		'sdd-data-assets-scan-detail',
		'sdd-data-assets-scan',
		'sdd-data-dict',
		'sdd-data-find-add',
		'sdd-data-find-compare',
		'sdd-data-find-details',
		'sdd-data-find-edit',
		'sdd-data-find-report',
		'sdd-data-find-task',
		'sdd-data-list-catalogue',
		'sdd-data-list-papers',
		'sdd-data-manager',
		'sdd-data-model',
		'sdd-database-detail',
		'sdd-database',
		'sdd-databse-file-detail',
		'sdd-feedback-engine',
		'sdd-file-detail',
		'sdd-file',
		'sdd-find-template',
		'sdd-import-data-list-new',
		'sdd-important-data-list',
		'sdd-key-position-person',
		'sdd-monitor',
		'sdd-personal-data-list',
		'sdd-report-details',
		'sdd-scan-manage',
		'sdd-sensitive-rules',
		'sdd-sys-group',
		'sdd-sys-set',
		'sdd-user-set',
		'sdd-vector-engine',
		'sdd-version-plugin',
		'sdd-work-order-verify',
		'sdd-workbench-check',
	'sdd-workbench')

SELECT
    menu_code AS original,
    regexp_replace(menu_code, '^(dsm-(dsmcp|dsmc|sdd|idm)-)', 'dsm-') AS new_menu_code
FROM ums_sys_menus
WHERE menu_code REGEXP '^dsm-';

SELECT
    parent_name AS original,
    regexp_replace(parent_name, '^(dsm-(dsmcp|dsmc|sdd|idm)-)', 'dsm-') AS new_menu_code
FROM ums_sys_menus
WHERE parent_name REGEXP '^dsm-';

SELECT
    function_id AS original,
    regexp_replace(function_id, '^(dsm-(dsmcp|dsmc|sdd|idm)-)', 'dsm-') AS new_menu_code
FROM ums_sys_role_function
WHERE function_id REGEXP '^dsm-';





UPDATE ums_sys_menus
SET menu_code = regexp_replace(menu_code, '^(dsm-(dsmcp|dsmc|sdd|idm)-)', 'dsm-')
WHERE menu_code REGEXP '^dsm-';


UPDATE ums_sys_menus
SET parent_name = regexp_replace(parent_name, '^(dsm-(dsmcp|dsmc|sdd|idm)-)', 'dsm-')
WHERE parent_name REGEXP '^dsm-';


UPDATE ums_sys_role_function
SET function_id = regexp_replace(function_id, '^(dsm-(dsmcp|dsmc|sdd|idm)-)', 'dsm-')
WHERE function_id REGEXP '^dsm-';

-- 查询是否有重复的菜单
SELECT
    menu_code,
    menu_name,
    parent_name,
    COUNT(*) AS duplicate_count
FROM
    ums_sys_menus
WHERE
    application = 'dsm_web'
  AND menu_category = 0
GROUP BY
    menu_code
HAVING
    COUNT(*) > 1

-- 查询系统内置菜单
SELECT
    *
FROM
    ums_sys_menus
WHERE
    menu_code IN (SELECT function_id FROM ums_sys_role_function WHERE role_id = 1)
ORDER BY
    menu_code